export const APP_PADDING = {
    ONE: 1,
    TWO: 2,
    THREE: 3,
    FOUR: 4,
    FIVE: 5,
    SIX: 6,
    SEVEN: 7,
    EIGHT: 8,
    NINE: 9,
    TEN: 10,
    ELEVEN: 11,
    TWELVE: 12,
    THIRTEN: 13,
    FOURTEN: 14,
    FIFTEN: 15,
    SIXTEN: 16,
    SEVENTEN: 17,
    EIGHTEN: 18,
    NINETEN: 19,
    TWENTY: 20,
};
export const APP_MARGIN = {
    ONE: 1,
    TWO: 2,
    THREE: 3,
    FOUR: 4,
    FIVE: 5,
    SIX: 6,
    SEVEN: 7,
    EIGHT: 8,
    NINE: 9,
    TEN: 10,
    ELEVEN: 11,
    TWELVE: 12,
    THIRTEN: 13,
    FOURTEN: 14,
    FIFTEN: 15,
    SIXTEN: 16,
    SEVENTEN: 17,
    EIGHTEN: 18,
    NINETEN: 19,
    TWENTY: 20,
};

export const APP_FONT_SIZE = {
    TWELVE: 12,
    THIRTEN: 13,
    FOURTEN: 14,
    FIFTEN: 15,
    SIXTEN: 16,
    SEVENTEN: 17,
    EIGHTEN: 18,
    NINETEN: 19,
    TWENTY: 20,
    TWENTY_ONE: 21,
    TWENTY_TWO: 22,
    TWENTY_THREE: 23,
    TWENTY_FOUR: 24,
    TWENTY_FIVE: 25,
    TWENTY_SIX: 26,
    TWENTY_SEVEN: 27,
    TWENTY_EIGHT: 28,
    TWENTY_NINE: 29,
    THIRTY: 30,
};

export const MODAL_INCIDENT_WIDTH = 100;
export const MODAL_INCIDENT_HEIGHT = 50;
